name: Bug Report
description: Report a problem so we can fix it
title: "[BUG] ~add a title~"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below with as much detail as possible.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: E.g., operating system, browser, app version, etc.
      placeholder: "Example: Ubuntu 22.04, Firefox 115, v1.2.3"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step description of how to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: Include console errors, stack traces, or screenshots if applicable.
      placeholder: "Paste here or drag and drop files"